### ISSUE TITLE
Open project in CLI

### ISSUE THREAD

**Issue by feitzi** [saurabhdaware/projectman#5]
Hi @saurabhdaware, very nice tool :)

Is it possible to add a way to jump directly in the CLI to the project root? So instead of open an IDE just jump to the project path in the current command line?

br

**Comment by saurabhdaware** [comment]
I am not sure if I fully understood this, Do you mean having a command like `pm jump` which will be equivalent to `cd /path/to/the/folder` without actually opening them?  I don't really think so it is worth having a different command for this since opening a project in IDE will also open their integrated terminals with the same path also I don't really want to flood projectman with too many features.

If you meant something else please do let me know. I am closing this for now in future if other people ask for this feature too then maybe I'll reopen this.

Thanks for creating issue do create issues if you have any other suggestions as well :D 

closing this for now.

**Comment by feitzi** [comment]
yes, exactly something like `jump`
Often I want just search something, or execute a command inside a project. Opening an IDE for that is mostly overkill.

**Comment by saurabhdaware** [comment]
For now, I guess I will keep this focused on opening and saving projects so maybe not now though thanks for your input :smile:

**Comment by saurabhdaware** [comment]
So I checked how we can implement this and apparently we can't simply use `exec('cd path')` since it runs commands in separate shell and the only way I found to achieve this is to create a shell script and then call that script from nodejs which would be super hacky to implement and will kind of ruin the scalability :(

**Comment by saurabhdaware** [comment]
`cd $(pm path)` added as an alternative for this in #9 
Thank you for your suggestion @feitzi 🎉
